### ISSUE TITLE
Is this project  in unfinish state?

### ISSUE THREAD

**Issue by GuoRuiLv** [cuba-labs/anonymous-access-demo#1]
This project can't be build successfully  

![image](https://user-images.githubusercontent.com/1725996/57832648-ba1c9a00-77ea-11e9-858d-70e0d78ce585.png)

**Comment by dtsaryov** [comment]
Hello @lugreen 

The project is based on 7.1-SNAPSHOT version of CUBA, but repositories that are used in it don't have latest changes.

I've added our public Nexus repo that has required version. Please check if everything is ok and close the issue

**Comment by GuoRuiLv** [comment]
Hi @dtsaryov ,

Thanks for your help.

I updated  the project, still has the problem:

**Comment by dtsaryov** [comment]
The sample is based on not released version of CUBA so please just wait until 7.1 will be released.
